### ISSUE TITLE
A lot of errors on CpanTesters

### ISSUE THREAD

**Issue by borisdaeppen** [borisdaeppen/EBook-MOBI-Image#1]
Asked question here: http://stackoverflow.com/questions/15906351/dependency-of-imageimlib2-on-cpantesters

**Comment by kimryan** [comment]
The synopsis for this module doesn't seem to show how you actually attach an image to the .mobi file you are creating. Only seems to show how to get a path to a rescaled image,  Would it be possible tp provide a full example?

 use EBook::MOBI::Image;
 my $p = EBook::MOBI::Image->new();

 my $img_path_small = $p->rescale_dimensions($img_path_big);

Also, your readme file is called README.md . Could it be changed to just README? Then it would show up as a link here http://search.cpan.org/~borisd/EBook-MOBI-Image-0.14/

**Comment by borisdaeppen** [comment]
Can you please open two issues? You mention two problems in an old and different issue, this is not a good way of reporting and bad for people later who search or even bring up solutions.

Please do so. Then I will come up with my answers ;-) And yes, you are right, the documentation for adding images lacks a bit. I should update that.

Thanks for you help! I appreciate your reporting.
