### ISSUE TITLE
Synopsis is missing instructions for attaching image files

### ISSUE THREAD

**Issue by kimryan** [borisdaeppen/EBook-MOBI-Image#2]
The synopsis for this module doesn't seem to show how you actually attach an image to the .mobi file you are creating. Only seems to show how to get a path to a rescaled image, Would it be possible to provide an example?

use EBook::MOBI::Image;
my $p = EBook::MOBI::Image->new();

my $img_path_small = $p->rescale_dimensions($img_path_big);

**Comment by borisdaeppen** [comment]
This should go in the Docs of EBook::MOBI, since this module is just for the separation of dependencies

**Comment by borisdaeppen** [comment]
Added hint in docs in commit 65dd96ea7933e8807f35113aa9494b3e022124bb

**Comment by borisdaeppen** [comment]
Added to EBook::MOBI https://github.com/borisdaeppen/EBook--MOBI/commit/ad38b85197bcd67e6907646dc7a44dc8fa8e0a72
