### ISSUE TITLE
 README.md should be renamed to README

### ISSUE THREAD

**Issue by kimryan** [borisdaeppen/EBook-MOBI-Image#3]
Your readme file is called README.md . Could it be changed to just README, which is standard practice? Then it would show up as a link here http://search.cpan.org/~borisd/EBook-MOBI-Image-0.14/

**Comment by borisdaeppen** [comment]
The .md is coming from Github. Would make sense to change it to a non-markup style. Or can CPAN display .pod? Github could...

**Comment by kimryan** [comment]
I looked at other CPAN modules that are in github, and they allow for a file called README, with no extension, you can see one see here https://github.com/PerlDancer/Dancer . Not sure where the .md extension comes from.

The README file should just be plain text and is normally a copy of the first part of you module documentation, with description and synopsis

**Comment by borisdaeppen** [comment]
renamed in commit 93dcffe5d1ed5e12652421c6ddc2c97e25f97e2a
